export interface Product{
  id: string;
  name: string;
  category: "fruits" | "vegetables" | "herbs" | "specialty";
  image: string;
  description: string;
  availability: "In Season" | "Year Round" | "Limited" | "Seasonal";
  packaging: string[];
}

export const products: Product[] = [
  {
    id: "mangoes",
    name: "Mangoes",
    category: "fruits",
    image: "/images/products/mango.png",
    description: "Sweet, juicy mangoes sourced from trusted orchards.",
    availability: "In Season",
    packaging: ["Single unit", "12 ct case"],
  },
  {
    id: "apples",
    name: "Apples",
    category: "fruits",
    image: "/images/products/apple.png",
    description: "Crisp and fresh apples with natural sweetness.",
    availability: "Year Round",
    packaging: ["1 kg bag", "20 lb box"],
  },
  {
    id: "bananas",
    name: "Bananas",
    category: "fruits",
    image: "/images/products/banana.png",
    description: "Fresh bananas ideal for retail and wholesale supply.",
    availability: "Year Round",
    packaging: ["Bunch", "18 kg case"],
  },
  {
    id: "oranges",
    name: "Oranges",
    category: "fruits",
    image: "/images/products/orange.png",
    description: "Juicy oranges rich in flavor and vitamin C.",
    availability: "Seasonal",
    packaging: ["10 kg box", "15 kg box"],
  },
  {
    id: "grapes",
    name: "Grapes",
    category: "fruits",
    image: "/images/products/grape.png",
    description: "Fresh green and black grapes for premium quality supply.",
    availability: "Seasonal",
    packaging: ["5 kg crate", "10 kg crate"],
  },

  {
    id: "tomatoes",
    name: "Tomatoes",
    category: "vegetables",
    image: "/images/products/tomato.png",
    description: "Fresh vine-ripened tomatoes sourced daily.",
    availability: "Year Round",
    packaging: ["10 lb box", "25 lb case"],
  },
  {
    id: "potatoes",
    name: "Potatoes",
    category: "vegetables",
    image: "/images/products/patato.png",
    description: "High-quality potatoes for wholesale supply.",
    availability: "Year Round",
    packaging: ["10 kg bag", "50 kg sack"],
  },
  {
    id: "onions",
    name: "Onions",
    category: "vegetables",
    image: "/images/products/onion.png",
    description: "Fresh onions suitable for bulk distribution.",
    availability: "Year Round",
    packaging: ["5 kg bag", "20 kg sack"],
  },
  {
    id: "carrots",
    name: "Carrots",
    category: "vegetables",
    image: "/images/products/carrot.png",
    description: "Crunchy orange carrots, freshly harvested.",
    availability: "Year Round",
    packaging: ["5 kg bunch", "10 kg box"],
  },
  {
    id: "cucumbers",
    name: "Cucumbers",
    category: "vegetables",
    image: "/images/products/cumumber.png",
    description: "Fresh cucumbers with high water content and crisp texture.",
    availability: "Seasonal",
    packaging: ["Box", "Crate"],
  },

  {
    id: "mint",
    name: "Mint",
    category: "herbs",
    image: "/images/products/mint.png",
    description: "Fresh mint leaves with strong aroma and flavor.",
    availability: "Year Round",
    packaging: ["Bunch", "Box"],
  },
  {
    id: "coriander",
    name: "Coriander",
    category: "herbs",
    image: "/images/products/coriander.png",
    description: "Fresh coriander used in daily cooking and garnishing.",
    availability: "Year Round",
    packaging: ["Bunch", "Box"],
  },
  {
    id: "basil",
    name: "Basil",
    category: "herbs",
    image: "/images/products/basil.png",
    description: "Aromatic basil leaves for culinary use.",
    availability: "Year Round",
    packaging: ["Bunch"],
  },
  {
    id: "parsley",
    name: "Parsley",
    category: "herbs",
    image: "/images/products/parsley.png",
    description: "Fresh parsley used in cooking and decoration.",
    availability: "Year Round",
    packaging: ["Bunch", "Box"],
  },
  {
    id: "dill",
    name: "Dill",
    category: "herbs",
    image: "/images/products/dill.png",
    description: "Fresh dill with a light, aromatic flavor.",
    availability: "Seasonal",
    packaging: ["Bunch"],
  },

  {
    id: "avocados",
    name: "Avocados",
    category: "specialty",
    image: "/images/products/avocado.png",
    description: "Creamy avocados ideal for premium markets.",
    availability: "Year Round",
    packaging: ["Single", "Box"],
  },
  {
    id: "broccoli",
    name: "Broccoli",
    category: "specialty",
    image: "/images/products/broccoli.png",
    description: "Fresh green broccoli with high nutritional value.",
    availability: "Year Round",
    packaging: ["Box", "Crate"],
  },
  {
    id: "zucchini",
    name: "Zucchini",
    category: "specialty",
    image: "/images/products/zucchini.png",
    description: "Fresh zucchini for cooking and grilling.",
    availability: "Seasonal",
    packaging: ["Box"],
  },
  {
    id: "mushrooms",
    name: "Mushrooms",
    category: "specialty",
    image: "/images/products/mushroom.png",
    description: "Fresh mushrooms for gourmet cooking.",
    availability: "Year Round",
    packaging: ["Tray", "Box"],
  },
  {
    id: "baby-corn",
    name: "Baby Corn",
    category: "specialty",
    image: "/images/products/baby-corn.png",
    description: "Tender baby corn used in stir-fry and salads.",
    availability: "Seasonal",
    packaging: ["Box"],
  },
];