export interface Product {
  id: string;
  name: string;
  category:
    | "fruits"
    | "vegetables"
    | "greens-salads"
    | "nuts"
    | "specialty"
    | "organics";
  image: string;
  description: string;
  availability: "In Season" | "Year Round" | "Limited";
  packaging: string[];
}

export const products: Product[] = [
  // ── FRUITS ──
  {
    id: "ambrosia-apples",
    name: "Ambrosia Apples",
    category: "fruits",
    image: "/images/products/ambrosia-apples.png",
    description:
      "Sweet, crisp apples with a honeyed flavor, perfect for fresh eating.",
    availability: "In Season",
    packaging: ["Bushel", "40 lb case"],
  },
  {
    id: "apricots",
    name: "Apricots",
    category: "fruits",
    image: "/images/products/apricots.png",
    description: "Juicy, tender apricots sourced at peak ripeness.",
    availability: "In Season",
    packaging: ["Flat", "Case"],
  },
  {
    id: "avocados",
    name: "Avocados",
    category: "fruits",
    image: "/images/products/Avocados.png",
    description:
      "Creamy, ready-to-eat avocados ideal for restaurants and grocers.",
    availability: "Year Round",
    packaging: ["Case of 48", "Case of 60"],
  },
  {
    id: "cantaloupe",
    name: "Cantaloupe",
    category: "fruits",
    image: "/images/products/cantaloupe.png",
    description: "Sweet, aromatic cantaloupe melons sourced fresh.",
    availability: "In Season",
    packaging: ["Case"],
  },
  {
    id: "cherries",
    name: "Cherries",
    category: "fruits",
    image: "/images/products/cherries.png",
    description: "Plump, sweet cherries available in season.",
    availability: "In Season",
    packaging: ["Flat", "5 lb box"],
  },
  {
    id: "clementines",
    name: "Clementines",
    category: "fruits",
    image: "/images/products/clementines.png",
    description:
      "Easy-peel, sweet clementines perfect for retail and food service.",
    availability: "Year Round",
    packaging: ["5 lb box", "Case"],
  },
  {
    id: "cosmic-crisp-apples",
    name: "Cosmic Crisp Apples",
    category: "fruits",
    image: "/images/products/cosmic-crisp-apples.png",
    description: "Crisp, juicy apples with a balanced sweet-tart flavor.",
    availability: "Year Round",
    packaging: ["Bushel", "40 lb case"],
  },
  {
    id: "figs",
    name: "Figs",
    category: "fruits",
    image: "/images/products/figs.png",
    description: "Delicate, sweet figs ideal for specialty menus.",
    availability: "Limited",
    packaging: ["Flat"],
  },
  {
    id: "fuji-apples",
    name: "Fuji Apples",
    category: "fruits",
    image: "/images/products/apples.png",
    description: "Crisp, sweet apples with a long shelf life.",
    availability: "Year Round",
    packaging: ["Bushel", "40 lb case"],
  },
  {
    id: "gala-apples",
    name: "Gala Apples",
    category: "fruits",
    image: "/images/products/gala-apples.png",
    description: "Mildly sweet, versatile apples great for any use.",
    availability: "Year Round",
    packaging: ["Bushel", "40 lb case"],
  },
  {
    id: "gold-delicious-apples",
    name: "Gold Delicious Apples",
    category: "fruits",
    image: "/images/products/gold-delicious-apples.png",
    description: "Sweet, golden apples perfect for snacking or baking.",
    availability: "Year Round",
    packaging: ["Bushel", "40 lb case"],
  },
  {
    id: "gold-kiwi",
    name: "Gold Kiwi",
    category: "fruits",
    image: "/images/products/gold-kiwi.png",
    description: "Smooth-skinned, sweet golden kiwi.",
    availability: "Limited",
    packaging: ["Case of 27", "Case of 33"],
  },
  {
    id: "granny-smith-apples",
    name: "Granny Smith Apples",
    category: "fruits",
    image: "/images/products/granny-smith-apples.png",
    description: "Tart, crisp apples ideal for baking and salads.",
    availability: "Year Round",
    packaging: ["Bushel", "40 lb case"],
  },
  {
    id: "grapefruit",
    name: "Grapefruit",
    category: "fruits",
    image: "/images/products/grapefruit.png",
    description: "Juicy, tangy grapefruit sourced fresh.",
    availability: "Year Round",
    packaging: ["Case of 27", "Case of 36"],
  },
  {
    id: "green-grapes",
    name: "Green Grapes",
    category: "fruits",
    image: "/images/products/green-grapes.png",
    description: "Crisp, sweet seedless green grapes.",
    availability: "Year Round",
    packaging: ["18 lb case"],
  },
  {
    id: "black-seedless-grapes",
    name: "Black Seedless Grapes",
    category: "fruits",
    image: "/images/products/black-seedless-grapes.png",
    description: "Sweet, juicy black seedless grapes.",
    availability: "Year Round",
    packaging: ["18 lb case"],
  },
  {
    id: "red-grapes",
    name: "Red Grapes",
    category: "fruits",
    image: "/images/products/red-grapes.png",
    description: "Sweet, crisp red seedless grapes.",
    availability: "Year Round",
    packaging: ["18 lb case"],
  },
  {
    id: "kiwi",
    name: "Kiwi",
    category: "fruits",
    image: "/images/products/kiwi.png",
    description: "Tangy, vitamin-rich green kiwi.",
    availability: "Year Round",
    packaging: ["Case of 27", "Case of 33"],
  },
  {
    id: "lemons",
    name: "Lemons",
    category: "fruits",
    image: "/images/products/lemons.png",
    description: "Fresh, juicy lemons for culinary and beverage use.",
    availability: "Year Round",
    packaging: ["Case of 95", "Case of 140"],
  },
  {
    id: "limes",
    name: "Limes",
    category: "fruits",
    image: "/images/products/limes.png",
    description: "Fresh, zesty limes for kitchens and bars.",
    availability: "Year Round",
    packaging: ["Case of 200", "Bag"],
  },
  {
    id: "mangoes",
    name: "Mangoes",
    category: "fruits",
    image: "/images/products/mangoe.png",
    description: "Sweet, tropical mangoes sourced fresh.",
    availability: "In Season",
    packaging: ["Case of 10", "Case of 12"],
  },
  {
    id: "nectarines",
    name: "Nectarines",
    category: "fruits",
    image: "/images/products/neticates.png",
    description: "Juicy, smooth-skinned nectarines.",
    availability: "In Season",
    packaging: ["Flat", "Case"],
  },
  {
    id: "white-nectarines",
    name: "White Nectarines",
    category: "fruits",
    image: "/images/products/white-neticates.png",
    description: "Sweet, low-acid white nectarines.",
    availability: "In Season",
    packaging: ["Flat", "Case"],
  },
  {
    id: "oranges",
    name: "Oranges",
    category: "fruits",
    image: "/images/products/oranges.png",
    description: "Juicy, fresh oranges for retail and food service.",
    availability: "Year Round",
    packaging: ["Case of 40", "Bag"],
  },
  {
    id: "peaches",
    name: "Peaches",
    category: "fruits",
    image: "/images/products/peaches.png",
    description: "Sweet, juicy peaches sourced in season.",
    availability: "In Season",
    packaging: ["Flat", "Case"],
  },
  {
    id: "pears",
    name: "Pears",
    category: "fruits",
    image: "/images/products/pears.png",
    description: "Crisp, sweet pears ideal for retail and food service.",
    availability: "Year Round",
    packaging: ["28 lb case"],
  },
  {
    id: "pineapples",
    name: "Pineapples",
    category: "fruits",
    image: "/images/products/pineapples.png",
    description: "Sweet, tropical pineapples sourced fresh.",
    availability: "Year Round",
    packaging: ["Case of 5", "Case of 6"],
  },
  {
    id: "pink-lady-apples",
    name: "Pink Lady Apples",
    category: "fruits",
    image: "/images/products/pink-lady-apples.png",
    description: "Crisp, sweet-tart apples with a vibrant pink hue.",
    availability: "Year Round",
    packaging: ["Bushel", "40 lb case"],
  },
  {
    id: "plums",
    name: "Plums",
    category: "fruits",
    image: "/images/products/plums.png",
    description: "Juicy, sweet plums sourced in season.",
    availability: "In Season",
    packaging: ["Flat", "Case"],
  },
  {
    id: "pomegranates",
    name: "Pomegranates",
    category: "fruits",
    image: "/images/products/pomegranates.png",
    description: "Vibrant, antioxidant-rich pomegranates.",
    availability: "Limited",
    packaging: ["Case"],
  },
  {
    id: "red-delicious-apples",
    name: "Red Delicious Apples",
    category: "fruits",
    image: "/images/products/red-delicious-apples.png",
    description: "Classic sweet, crisp red apples.",
    availability: "Year Round",
    packaging: ["Bushel", "40 lb case"],
  },

  // ── VEGETABLES ──
  {
    id: "beets",
    name: "Beets",
    category: "vegetables",
    image: "/images/products/beets.png",
    description: "Fresh, earthy beets sourced from trusted growers.",
    availability: "Year Round",
    packaging: ["12x500g case"],
  },
  {
    id: "broccoli",
    name: "Broccoli",
    category: "vegetables",
    image: "/images/products/broccolis.png",
    description: "Fresh, crisp broccoli crowns.",
    availability: "Year Round",
    packaging: ["Crown case"],
  },
  {
    id: "cabbage",
    name: "Cabbage",
    category: "vegetables",
    image: "/images/products/cabbage.png",
    description: "Crisp, fresh cabbage for retail and food service.",
    availability: "Year Round",
    packaging: ["16 ct case"],
  },
  {
    id: "carrots",
    name: "Carrots",
    category: "vegetables",
    image: "/images/products/carrots.png",
    description: "Fresh, crunchy jumbo carrots sourced consistently.",
    availability: "Year Round",
    packaging: ["25 lb bag", "50 lb bag"],
  },
  {
    id: "cauliflower",
    name: "Cauliflower",
    category: "vegetables",
    image: "/images/products/cauliflower.png",
    description: "Fresh, firm cauliflower heads.",
    availability: "Year Round",
    packaging: ["9-12 ct case"],
  },
  {
    id: "celery",
    name: "Celery",
    category: "vegetables",
    image: "/images/products/celery.png",
    description: "Crisp, fresh celery stalks.",
    availability: "Year Round",
    packaging: ["24 ct case"],
  },
  {
    id: "cucumbers",
    name: "Cucumbers",
    category: "vegetables",
    image: "/images/products/cucumbers.png",
    description: "Fresh, crisp cucumbers sourced daily.",
    availability: "Year Round",
    packaging: ["Case"],
  },
  {
    id: "eggplant",
    name: "Eggplant",
    category: "vegetables",
    image: "/images/products/eggplant.png",
    description: "Fresh, firm eggplant for culinary use.",
    availability: "Year Round",
    packaging: ["Case"],
  },
  {
    id: "onions",
    name: "Onions",
    category: "vegetables",
    image: "/images/products/onions.png",
    description: "Fresh onions sourced for consistent quality.",
    availability: "Year Round",
    packaging: ["50 lb bag", "25 lb bag"],
  },
  {
    id: "peppers",
    name: "Peppers",
    category: "vegetables",
    image: "/images/products/peppers.png",
    description: "Fresh bell peppers in a variety of colors.",
    availability: "Year Round",
    packaging: ["Case"],
  },
  {
    id: "potatoes",
    name: "Potatoes",
    category: "vegetables",
    image: "/images/products/potatoes.png",
    description: "Fresh potatoes sourced for retail and food service.",
    availability: "Year Round",
    packaging: ["50 lb bag", "60-70 ct", "80 ct", "100 ct"],
  },
  {
    id: "tomatoes",
    name: "Tomatoes",
    category: "vegetables",
    image: "/images/products/tomatoes.png",
    description: "Fresh, vine-ripened tomatoes.",
    availability: "Year Round",
    packaging: ["5x6 case", "6x6 case", "Roma case"],
  },
  {
    id: "zucchini",
    name: "Zucchini",
    category: "vegetables",
    image: "/images/products/zucchinis.png",
    description: "Fresh, tender zucchini sourced daily.",
    availability: "Year Round",
    packaging: ["Fancy case", "Medium case"],
  },

  // ── GREENS & SALADS ──
  {
    id: "arugula",
    name: "Arugula",
    category: "greens-salads",
    image: "/images/products/arugula.png",
    description: "Peppery, fresh arugula greens.",
    availability: "Year Round",
    packaging: ["2 lb box"],
  },
  {
    id: "chopped-romaine",
    name: "Chopped Romaine",
    category: "greens-salads",
    image: "/images/products/chopped-romaine.png",
    description: "Pre-chopped romaine lettuce, ready to use.",
    availability: "Year Round",
    packaging: ["Case"],
  },
  {
    id: "coleslaw",
    name: "Coleslaw Mix",
    category: "greens-salads",
    image: "/images/products/coleslaw.png",
    description: "Pre-shredded coleslaw blend, ready to use.",
    availability: "Year Round",
    packaging: ["4x5lb case"],
  },
  {
    id: "heritage-lettuce",
    name: "Heritage Lettuce",
    category: "greens-salads",
    image: "/images/products/heritage-lettuce.png",
    description: "Premium heritage lettuce blend.",
    availability: "Year Round",
    packaging: ["Case"],
  },
  {
    id: "kale",
    name: "Kale",
    category: "greens-salads",
    image: "/images/products/kale.png",
    description: "Fresh, nutrient-dense kale.",
    availability: "Year Round",
    packaging: ["2 lb box"],
  },
  {
    id: "lettuce",
    name: "Lettuce",
    category: "greens-salads",
    image: "/images/products/lettuce.png",
    description: "Crisp, fresh wrap lettuce sourced daily.",
    availability: "Year Round",
    packaging: ["24 ct case"],
  },
  {
    id: "salad-mix",
    name: "Salad Mix",
    category: "greens-salads",
    image: "/images/products/salad-mix.png",
    description: "Ready-to-use mixed salad greens.",
    availability: "Year Round",
    packaging: ["4x5lb case"],
  },
  {
    id: "shredded-lettuce",
    name: "Shredded Lettuce",
    category: "greens-salads",
    image: "/images/products/shredded-lettuce.png",
    description: "Pre-shredded lettuce, ready to use.",
    availability: "Year Round",
    packaging: ["1/8 case"],
  },
  {
    id: "spinach",
    name: "Spinach",
    category: "greens-salads",
    image: "/images/products/spinach.png",
    description: "Fresh, tender spinach leaves.",
    availability: "Year Round",
    packaging: ["4 lb box", "5x2lb case"],
  },
  {
    id: "spring-mix",
    name: "Spring Mix",
    category: "greens-salads",
    image: "/images/products/spring-mix.png",
    description: "Delicate, ready-to-use spring greens mix.",
    availability: "Year Round",
    packaging: ["3 lb box"],
  },

  // ── NUTS ──
  {
    id: "almonds",
    name: "Almonds",
    category: "nuts",
    image: "/images/products/Nuts/Almonds.png",
    description: "Premium quality raw almonds, new crop.",
    availability: "Year Round",
    packaging: ["Case"],
  },
  {
    id: "walnuts",
    name: "Walnuts",
    category: "nuts",
    image: "/images/products/Nuts/Walnuts.png",
    description: "Fresh, premium Eureka Dark Chandler walnuts.",
    availability: "Year Round",
    packaging: ["Case"],
  },

  // ── SPECIALTY ──
  {
    id: "peeled-garlic",
    name: "Peeled Garlic",
    category: "specialty",
    image: "/images/products/peeled-garlic.png",
    description: "Pre-peeled garlic cloves, ready to use.",
    availability: "Year Round",
    packaging: ["6x3 case"],
  },

  // ── ORGANICS ──
  {
    id: "organic-beets",
    name: "Organic Beets",
    category: "organics",
    image: "/images/products/organic-beets.png",
    description: "Certified organic, cooked and peeled beets.",
    availability: "Year Round",
    packaging: ["Case"],
  },
  {
    id: "organic-broccoli",
    name: "Organic Broccoli",
    category: "organics",
    image: "/images/products/organic-broccoli.png",
    description: "Certified organic broccoli crowns.",
    availability: "Year Round",
    packaging: ["Case"],
  },
  {
    id: "organic-cauliflower",
    name: "Organic Cauliflower",
    category: "organics",
    image: "/images/products/organic-cauliflower.png",
    description: "Certified organic cauliflower, 12 count.",
    availability: "Year Round",
    packaging: ["12 ct case"],
  },
  {
    id: "organic-celery",
    name: "Organic Celery",
    category: "organics",
    image: "/images/products/organic-celery.png",
    description: "Certified organic celery, 30 count sleeve.",
    availability: "Year Round",
    packaging: ["30 ct sleeve"],
  },
];
